---
title: "Determine the most effective cancer treatment based on cervix type"
output: html_document
---

# Problem:

Cervical Cancer is so easy to prevent if caught in its pre-cancerous stage that every woman should have access to effective, life-saving treatment no matter where they live. Today, women worldwide in low-resource settings are benefiting from programs where cancer is identified and treated in a single visit. However, due in part to lacking expertise in the field, one of the greatest challenges of these cervical cancer screen and treat programs is determining the appropriate method of treatment which can vary depending on patients' physiological differences.

Especially in rural parts of the world, many women at high risk for cervical cancer are receiving treatment that will not work for them due to the position of their cervix. This is a tragedy: health providers are able to identify high risk patients, but may not have the skills to reliably discern which treatment which will prevent cancer in these women. Even worse, applying the wrong treatment has a high cost. A treatment which works effectively for one woman may obscure future cancerous growth in another woman, greatly increasing health risks.

# Objective:

MobileODT offers a Quality Assurance workflow to support remote supervision which helps healthcare providers make better treatment decisions in rural settings. However, their workflow would be greatly improved given the ability to make real-time determinations about patients' treatment eligibility based on cervix type.

So, the main objective is to develop an algorithm which accurately identifies a woman's cervix type based on images. Doing so will prevent ineffectual treatments and allow healthcare providers to give proper referral for cases that require more advanced treatment.

# Data Set:

All the types of cervix data is required along with the cancer treatmnet methods for each type that are advisable. Kaggle site provides all the traning data and image data of the stages of the cervix.

# Solution:

Come up with some algorithm that could classify the cervix types based on images and suggest appropriate cancer treatment.

# Deliverables:

Block of code that can predict the solution to the problem, Rmd document which explains the process followed and powerpoint presentation of the project.